/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("edu.sc.seis.launch4j") version "4.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    //mainClass = "org.example.App"
    mainClass = "org.memoro.Driver"
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "org.memoro.Driver" // Replace with your main class
        )
    }
}

// launch4j {
//     mainClassName.set("org.memoro.Driver")
//     outfile.set("MyApp.exe")
// }

tasks.withType<edu.sc.seis.launch4j.tasks.DefaultLaunch4jTask> {
    outfile.set("${"Memoro"}.exe")
    mainClassName.set("org.memoro.Driver")
    //icon.set("$projectDir/icons/myApp.ico")
    productName.set("My App")
}
